name: update-csproj-version

on: [ workflow_dispatch ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Chackout Code
      uses: actions/checkout@v3

    - name: Check Release View
      uses: Hedgehogs0808/UpdateCsprojectVersion@1.0.0
      with:
        targetDir: .\src
        repoList: .\ref\ref_repository_list.csv
        isCommit: true
        addTag: true
        githubToken: ${{ secrets.GH_TOKEN }}
        updateUnit: 15

